### PR TITLE
Core Pages

### PR DESCRIPTION
**Pull request by ishpaul777**
This Pr has redesign changes for Core pages
- [x] Posts
- [x] pages
- [x] Tags
- [x] Category
- [x] Media

### CODE REVIEW

**Review by surajmn1 — CHANGES_REQUESTED** [review]
- [ ] fix the table words breaking in the core index pages in mobile view , they seemed to be fine in post index page but other places they are breaking.

- [x] make table rows clickable(on click it should go to the edit post/page ) for page and post index pages so that user can edit a post/page by clicking on the row instead of having a redundant edit post button , and add icons as in figma .

**Comment by surajmn1** [comment]
- [x] fix bugs in seo drawer of edit post/page . drawer is not extending over underlying section and gets stuck on clicking outside , back or close icon . 

- [x] fix details section in edit page not collapsing 

- [x] fix the date wrapping in details section of edit page .

**Comment by surajmn1** [comment]
@ishpaul777 

- [x] fix collapse sections color in edit post component . its currently greyish and is not matching with the color outside the section as required in figma


- [x] fix collapse section icons to have grey round border around them as in figma . 

- [x] date is still wrapping in edit page. 
Screenshot 2023-04-04 at 5 09 49 PM

**Comment by surajmn1** [comment]
@ishpaul777 
- [x] fix paddings , text colors in collapsible sections edit tag and media  as in figma 
Screenshot 2023-04-05 at 1 39 54 PM

current view doesnt have padding and collapse text color
Screenshot 2023-04-05 at 1 41 48 PM

- [x] fix this bug of text showing up under edit media page 
Screenshot 2023-04-05 at 1 46 20 PM

**Comment by surajmn1** [comment]
@ishpaul777 
- [ ] fix the table words breaking in the core index pages in mobile view , they seemed to be fine in post index page but other places they are breaking.

possible fixes to check : 
adding scroll={{x: “100vw”}} prop in tables and adding onCell function for columns in which cells are words are breaking 
up into letters . 
```
const columns = [
    {
      title: 'Title',
      dataIndex: 'title',
      key: 'title',
      width: 400,
      onCell: () => {.  // here ..
        return {
           style: {
              minWidth: 200,
           }
        }
     },
      render: (_, item) => (
        <Link to={`/pages/${item.id}/edit`}>
          <Typography.Text style={{ fontSize: '1rem', color: '#101828' }} strong>
            {item.title}
          </Typography.Text>
          {/*
          {item.published_date && (
            <p style={{ color: 'CaptionText' }}>
              Published on {dayjs(item.published_date).format('MMMM Do YYYY')}
            </p>
          )}
          <p style={{ color: 'CaptionText' }}>by {getAuthorsList(item.authors)}</p>
          */}
        </Link>
      ),

**Comment by surajmn1** [comment]
@ishpaul777 
- [x] fix missing breadcrumbs in edit tags , media etc .
   it should be like for 
   creating a tag .. tag > New tag
   for updating/editing a tag .. tag > [tagName] 

current view 
Screenshot 2023-04-05 at 4 09 31 PM
required view in figma 
Screenshot 2023-04-05 at 4 11 57 PM

**Comment by surajmn1** [comment]
@ishpaul777 
- [x] fix column lengths in index pages , they are too long now .
Screenshot 2023-04-05 at 6 18 13 PM

**Comment by surajmn1** [comment]
@ishpaul777 
- [x] fix this error

Screenshot 2023-04-06 at 11 15 15 AM

**Comment by surajmn1** [comment]
@ishpaul777 

- [x] fix fonts for collapse section description text in collapse text . example : look at the font for "general" in the collapse sections in the below images. 

- [x] fix category , tag , media edit pages to be mobile responsive . 

current view for media edit 
Screenshot 2023-04-06 at 12 53 24 PM

view required 
https://www.figma.com/file/DxpIIOfooHJfsZuPtgLCyP/Website?node-id=3860-206188&t=bR07NxZi5Ee8yCNH-0

Screenshot 2023-04-06 at 12 54 34 PM

**Comment by surajmn1** [comment]
@ishpaul777 
- [x] remove draft, ready being appended next to status icons in post index page. 
Screenshot 2023-04-07 at 12 05 15 PM

- [x] remove unslapash urls used for placeholder image.

**Comment by surajmn1** [comment]
@ishpaul777 

- [ ] fix delete posts modal creating black background for modal mask . 

Screenshot 2023-04-11 at 3 14 34 PM

- [ ] fix light greyish border over search icon in index pages , try using button with type = text prop and check . 

sketchpad pro_sp2j36mz2rxj710mc4sfp_p2

**Comment by surajmn1** [comment]
@ishpaul777 

- [ ] fix broken delete flow in index pages . example in delete posts index page after we click delete it tries to navigate to that deleted post , due to the onClick event being propagated . 
```  
  <Modal
                open={modalOpen}
                closable={false}
                centered
                width={311}
                className="delete-modal-container"
                cancelButtonProps={{ type: 'text', style: { color: '#000' } }}
                style={{
                  borderRadius: '18px',
                }}
                onOk={(e) => {// Add below lines in modals for ok handler wherever required . 
                  e.stopPropagation();
                  dispatch(deletePost(item.id)).then(() => fetchPosts());
                  setModalOpen(false);
                }}
                onCancel={(e) => {
                  e.stopPropagation();
                  setModalOpen(false);
                }}
              >

**Comment by surajmn1** [comment]
@ishpaul777 
- [ ] fix posts getting published twice when we click on publish button which is outside drawer . 
Screenshot 2023-04-25 at 4 07 13 PM

- [ ] please check all CRUD operations on every entity in core pages , posts etc...fix if any issues .

**Comment by surajmn1** [comment]
- [ ] @ishpaul777  fix post edit page drawer breaking .
Screenshot 2023-05-01 at 1 37 35 PM

**Comment by surajmn1** [comment]
@ishpaul777

- [ ] fix  publised date doesnt get picked up in edit screens 

Screenshot 2023-05-01 at 2 25 47 PM

**Comment by ishpaul777** [comment]
@surajmn1  could you explain the publised date doesnt get picked up issue and how to recreate

**Comment by surajmn1** [comment]
@ishpaul777 
the published date field isnt getting populated for a published post/page when opened in edit mode.

**Pull request merged**
